services:
  rails:
    build:
      context: .
      dockerfile: docker/Dockerfile.overlay
    image: rotta-chatwoot:v4.17.0-custom-v1
    env_file:
      - .env
    volumes:
      - storage_data:/app/storage
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["sh", "-c", "bundle exec rails db:chatwoot_prepare && exec bundle exec rails s -p 3000 -b 0.0.0.0"]
    restart: always

  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile.overlay
    image: rotta-chatwoot:v4.17.0-custom-v1
    env_file:
      - .env
    volumes:
      - storage_data:/app/storage
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    restart: always

volumes:
  storage_data:
